version: '3.7'

services:
  mongo:
    container_name: mongolocal
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE= user
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: